### PR TITLE
change output

### PR DESCRIPTION
**Pull request by SamiSoftB**
## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Comment by denrou** [comment]
Need some unit test to make sure it works

**Comment by denrou** [comment]
And in your change, if `output_dataframe` is False, then you return the result from warp10 as is. I think it would be best to pass this parameter to the `desanitize` function so GTS are still output as dataframes but list of GTS are returned as a list of dataframes instead of a single dataframe.
We could have something like:

```
def exec(..., raw=FALSE, bind_lgts=FALSE)
  ...
  if raw:
    return res
  return desanitize(res, bind_lgts)

def desanitize(x, bind_lgts=FALSE):
  if is_lgts(x):
    if bind_lgts:
      return desanitize_lgts(x)
    else:
      return [desanitize(xx) for xx in x]
```

**Comment by denrou** [comment]
And also, it's nice to use a template for the PR description, but you should edit it to explain the change and why it is needed

**Comment by SamiSoftB** [comment]
moved changes to another branch

**Pull request closed without merging**
